### ISSUE TITLE
Explore User Interfaces

### ISSUE THREAD

**Issue by anushkmittal** [jaym93/ctxmgmt#4]
Possible choices right now:

- iOS app with watchOS extension
- Slack Bot
- Alexa Voice Assistant
- Google Actions (Visual & TTS)
- Messenger Bot

maybe something else.. need to find the best fit (or maybe multiple, prioritized)

**Comment by jaym93** [comment]
Since we're using AWS, do you think it's easier to do Alexa? We'll show off two modalities, so, I'd say voice and chatbot are more novel and less time-consuming than a UI (although Google Actions should roll all of them into one)

See whatever suits you well in terms of skills and time, I have the skeleton code of Slack Bot on my github if you plan to go that route.

**Comment by anushkmittal** [comment]
@jaym93 can you post the slack code? I’ll probably do Slack Bot or Google Actions as first preference and then maybe we c an go for an iOS/watchOS extension based time and need.

**Comment by jaym93** [comment]
@anushkmittal  #7 should give you the Slack code. Let me know if you have questions or can't get it running. I've shared credentials with you on Slack.
