### ISSUE TITLE
GET generated events

### ISSUE THREAD

**Issue by anushkmittal** [jaym93/ctxmgmt#6]
things to consider?

- Is there a key that I'd like to filter by?
- Do I need all records to access?
- Should I use ElasticSearch?

**Comment by jaym93** [comment]
I think the "what" should be an in-patient parameter, so it'll be `url/object/?where=_someLocation_`, so *what* will be the filtering criteria.

Elastic search is a good idea, since it's the more scalable solution. Importing the whole database might not be optimal if we have a few thousand records, and it's not best practice either - the processing time on the server will be very, very little compared to the overhead of sending all the information, running search on the client and returning the information.

**Comment by anushkmittal** [comment]
Relevant references (note to self)

1. Using Query for Filter: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html

2. Using CloudSearch:
https://docs.aws.amazon.com/cloudsearch/latest/developerguide/searching-dynamodb-data.html

**Comment by anushkmittal** [comment]
Need a way to integrate lambda function with web hook integration from DialogFlow
